import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSiderbar from "@/components/ui/AppSiderbar";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { cookies } from "next/headers";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html lang="en"  suppressHydrationWarning>
      <body
        className=""
      >
        <ThemeProvider
             attribute="class"
             defaultTheme="system"
             enableSystem
             disableTransitionOnChange
          >
          <SidebarProvider defaultOpen={defaultOpen}>
        <AppSiderbar />
        <main className="">
          <Navbar />
          
          <div className=" ">{children}</div>
          
        </main>
        </SidebarProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
